### ISSUE TITLE
Restricted Comonads

### ISSUE THREAD

**Issue by gmpl** [gmpl/FsControl#40]
We have restricted instances for many Type-Methods but particularly those for <code>Extract</code> (potential empty lists) might need to be removed.
The reason is that they might fail at runtime, whereas the restricted <code>string</code> instance for <code>Map</code> will fail at compile time.
May be we can create something like <code>TryExtract</code> and then it will be safe to add those instances there.

**Comment by mausch** [comment]
:+1:
