### ISSUE TITLE
Skip and Take throw Exception.

### ISSUE THREAD

**Issue by gmpl** [gmpl/FsControl#46]
An exception is thrown when outside the bounds but that's a problem when using <code>seq</code> aiming for laziness, it will force you to check first the length of the sequence.
That's how they're implemented in F# but I prefer the Linq implementation which works as Haskell's drop and take, in those cases it returns an empty list which logically represents 'no results'.

**Comment by atifaziz** [comment]
The F# equivalent of [`Take`](https://msdn.microsoft.com/en-us/library/vstudio/bb503062(v=vs.100).aspx) from LINQ is called [`truncate`](https://msdn.microsoft.com/en-us/library/ee370325.aspx) that does not throw if the sequence has fewer elements than the specified count.

**Comment by gmpl** [comment]
So, may be can we leave them as they are and add another 2 functions: <code>drop</code> and <code>truncate</code> with that (safe) behaviour.

**Comment by gmpl** [comment]
I used the name <code>Limit</code> instead of <code>Truncate</code> because <code>Truncate</code> will conflict with the method of the same name for Numerics.
